### ISSUE TITLE
Bug: Configuration cannot be done via GUI

### ISSUE THREAD

**Issue by Exponent4806** [hgiesel/anki_stats_plus#13]
When I try to configure the add-on via GUI an error appears:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.10.10 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.1.26-1-MANJARO-x86_64-with-glibc2.37
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-05-04 16:21:22
Add-ons possibly involved: ⁨Stats Plus⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 971, in onConfig
    ret = act()
  File "/home/m/.local/share/Anki2/addons21/1009670238/src/addon_manager.py", line 31, in show_settings
    dialog = Settings(addons, set_settings)
  File "/home/m/.local/share/Anki2/addons21/1009670238/gui/settings.py", line 13, in __init__
    self.ui.setupUi(self)
  File "/home/m/.local/share/Anki2/addons21/1009670238/gui/forms/settings_ui.py", line 26, in setupUi
    self.deckBrowser = GraphList(self.deckbrowser_tab)
  File "/home/m/.local/share/Anki2/addons21/1009670238/gui/graph_list.py", line 23, in __init__
    self.ui.setupUi(self)
  File "/home/m/.local/share/Anki2/addons21/1009670238/gui/forms/graph_list_ui.py", line 24, in setupUi
    self.list.setMovement(QtWidgets.QListView.Snap)
  File "/usr/lib/python3.10/site-packages/aqt/qt/qt5_compat.py", line 342, in __getattr__
    enum = getattr(type, enum_name)
AttributeError: type object 'QListView' has no attribute 'BrowserLayout'

------------
Debug Info:
    
    Anki 2.1.61 (0c1eaf4c) Python 3.10.10 Qt 6.5.0 PyQt 6.5.0
    Platform: Linux-6.1.26-1-MANJARO-x86_64-with-glibc2.37
    Flags: frz=False ao=True sv=3
    Add-ons, last update check: 2023-05-04 16:21:22
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-09-27T02:28, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T21:24, 'None', '']
    AnkiConnect ['2055492159', 2023-04-11T19:20, 'None', '']
    Batch Editing ['291119185', 2019-06-02T20:47, 'None', '']
    Edit Field During Review Cloze ['385888438', 2022-06-27T11:48, '6.13', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
    Opening the same window multiple time ['354407385', 2020-05-16T02:59, 'None', '']
    Paste Images As WebP ['1151815987', 2023-04-29T15:08, 'None', '']
    Review Hotmouse ['1928346827', 2022-05-17T06:25, '2.6', mod]
    Stats Plus ['1009670238', 2021-03-04T13:23, 'None', '']
    ZIM Reader ['951350249', 2023-02-21T22:12, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1009670238 1151815987 1374772155 1928346827 2055492159 291119185 354407385 385888438 817108664 874215009 951350249
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Exponent4806** [comment]
The error also happens when inactivating all the other add-ons.
