### ISSUE TITLE
Clicking in the graphs conflicts with review heatmap

### ISSUE THREAD

**Issue by PHZCosta** [hgiesel/anki_stats_plus#2]
When I click in the graphs I receive the following error message:
Error
```
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-07 16:18:04

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 36, in cmd
  File "aqt\webview.py", line 135, in _onCmd
  File "aqt\webview.py", line 580, in _onBridgeCmd
  File "<decorator-gen-22>", line 2, in _linkHandler
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\****\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 69, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "C:\Users\pedro\AppData\Roaming\Anki2\addons21\877182321\column.py", line 13, in _linkHandler
    (cmd, arg) = url.split(":")
ValueError: too many values to unpack (expected 2)

```

This only happens with the graphs in the "Deck Browser" tab, in the other tabs they work fine.

**Comment by hgiesel** [comment]
This seems to be an incompatibility with Review Heatmap. I cannot recreate this without any other add-ons.
